# Generated by Django 3.0.5 on 2020-04-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('briefDesc', models.CharField(max_length=500)),
                ('detailedDesc', models.CharField(max_length=500)),
            ],
        ),
    ]
