# Generated by Django 3.0.5 on 2020-05-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=500)),
            ],
        ),
    ]
