# Generated by Django 2.2.11 on 2020-05-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogger',
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
    ]
