# Generated by Django 2.2.11 on 2020-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
