# Generated by Django 2.2.11 on 2020-05-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_category_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='createdAat',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
