# Generated by Django 2.2.11 on 2020-05-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_auto_20200518_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='createdAat',
            new_name='createdAt',
        ),
    ]
