# Generated by Django 2.2.11 on 2020-05-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_auto_20200518_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
