# Generated by Django 2.2.11 on 2020-05-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20200518_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='technologies',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
