# Generated by Django 2.2.11 on 2020-06-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0019_auto_20200621_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadpost',
            name='thred',
        ),
        migrations.AddField(
            model_name='forumthread',
            name='body',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threadpost',
            name='thread',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restapi.ForumThread'),
            preserve_default=False,
        ),
    ]
