# Generated by Django 2.2.11 on 2020-06-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0020_auto_20200621_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showALRM',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showEvents',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showTDL',
            field=models.BooleanField(default=True),
        ),
    ]
