# Generated by Django 2.2.11 on 2020-06-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0022_taskcontribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcontribution',
            old_name='poster',
            new_name='user',
        ),
    ]
