# Generated by Django 2.2.11 on 2020-06-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0025_activity_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activityType',
            field=models.PositiveSmallIntegerField(choices=[(1, 'project'), (2, 'forum'), (3, 'registered'), (4, 'contributed')], default=1),
            preserve_default=False,
        ),
    ]
