# Generated by Django 2.2.11 on 2020-06-21 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0026_activity_activitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcontribution',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
