# Generated by Django 2.2.11 on 2020-06-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0027_taskcontribution_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcontribution',
            name='progress',
            field=models.PositiveSmallIntegerField(choices=[(1, 'progress'), (2, 'validated')], default=1),
            preserve_default=False,
        ),
    ]
