# Generated by Django 2.2.11 on 2020-06-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0028_taskcontribution_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='showActs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showLeaders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showNews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showRNDM',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showStats',
            field=models.BooleanField(default=True),
        ),
    ]
