# Generated by Django 2.2.11 on 2020-06-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0029_auto_20200622_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_type',
            new_name='userType',
        ),
    ]
